manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 0f7c11248a1ddb7c6559064c2a1e7a3c446d5d55
      import: app/west.yml
  self:
    path: config
